//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioStreamer.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RadioStreamerDBEntities1 : DbContext
    {
        public RadioStreamerDBEntities1()
            : base("name=RadioStreamerDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Channel> Channel { get; set; }
        public virtual DbSet<Favourite> Favourite { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<Rating> Rating { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
        public virtual DbSet<TagsChannels> TagsChannels { get; set; }
        public virtual DbSet<User> User { get; set; }
    
        public virtual ObjectResult<CalculateRecommendation_Result> CalculateRecommendation(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalculateRecommendation_Result>("CalculateRecommendation", userNameParameter);
        }
    }
}
