//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioStreamer.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RadioStreamerDB : DbContext
    {
        public RadioStreamerDB()
            : base("name=RadioStreamerDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Channel> Channel { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
        public virtual DbSet<TagsChannels> TagsChannels { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Favourite> Favourite { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<Rating> Rating { get; set; }
    }
}
